In [15]:
from numpy import array
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.text import Tokenizer

In [25]:
# define documents
docs = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!',
		'Weak',
		'Poor effort!',
		'not good',
		'poor work',
		'Could have done better.']
# define class labels
labels = array([1,1,1,1,1,0,0,0,0,0])
# integer encode the documents
vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)
# pad documents to a max length of 4 words
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)
# define the model
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
#model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
# summarize the model
print(model.summary())
# fit the model
model.fit(padded_docs, labels, epochs=50, verbose=0)
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))

[[14, 30], [37, 18], [23, 48], [13, 18], [14], [9], [42, 48], [40, 37], [42, 18], [38, 24, 30, 25]]
[[14 30  0  0]
 [37 18  0  0]
 [23 48  0  0]
 [13 18  0  0]
 [14  0  0  0]
 [ 9  0  0  0]
 [42 48  0  0]
 [40 37  0  0]
 [42 18  0  0]
 [38 24 30 25]]
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 4, 8)              400       
_________________________________________________________________
dense_1 (Dense)              (None, 4, 1)              9         
Total params: 409
Trainable params: 409
Non-trainable params: 0
_________________________________________________________________
None


ValueError: A target array with shape (10, 1) was passed for an output of shape (None, 4, 1) while using as loss `binary_crossentropy`. This loss expects targets to have the same shape as the output.

In [24]:
test = ['very nice food','excellent']
tokenizer = Tokenizer()
tokenizer.fit_on_texts(test)
test_encoded = tokenizer.texts_to_sequences(test)
#test_encoded = [one_hot(d, vocab_size) for d in test]
print(test_encoded)
test_padded = pad_sequences(test_encoded, maxlen=max_length, padding='post')
test_padded

[[1, 2, 3], [4]]


array([[1, 2, 3, 0],
       [4, 0, 0, 0]], dtype=int32)

In [23]:
model.predict_classes(test_padded)

array([[0],
       [1]], dtype=int32)